name: Custom Workflow
on:
 pull_request:
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: First Job
     run: |
      echo Successfully made the custom workflow 
      echo value of the event is: ${{github.event_name}}
      echo Value of the github variable is: ${{github}}
  
