name: Custom Workflow
on:
 pull_request:
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Github Variable Properties
     run: |
      echo Successfully made the custom workflow 
      echo value of the event is: ${{github.event_name}}
      for key in "${!github[@]}"; 
      do
       echo "$key=${github[$key]}"
      done
  
